apiVersion: v1
kind: ConfigMap
metadata:
  name: movies-config
  namespace: movies
data:
  POSTGRES_USER: "postgres"
  POSTGRES_DB: "moviesdb"
  DB_HOST: "movies-db"
  DB_PORT: "5432"
  RECOMMENDER_URL: "http://recommender:5001"
